# Generated by Django 3.1.5 on 2022-01-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_system', '0002_courseenroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillHotWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('hot_word', models.CharField(max_length=100)),
            ],
        ),
    ]
