# Generated by Django 3.1.5 on 2022-01-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('course_system', '0006_studentdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregisterby',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_map', to='user.profile'),
        ),
    ]
