# Generated by Django 3.1.2 on 2021-12-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passout_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='placement_year',
            field=models.IntegerField(null=True),
        ),
    ]
