# Generated by Django 3.1.2 on 2021-12-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211224_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('CIVIL', 'CIVIL'), ('ECE', 'ECE'), ('MECH', 'MECH')], max_length=30, null=True),
        ),
    ]
